#ifndef HASHRATE_CHART_LAYOUT_H
#define HASHRATE_CHART_LAYOUT_H

#define HASHRATE_CHART_LEFT_GUTTER 70
#define HASHRATE_CHART_HEIGHT_REDUCTION 140
#define HASHRATE_CHART_BOTTOM_OFFSET 48
#define HASHRATE_CHART_TOP_PADDING 8
#define HASHRATE_CHART_BOTTOM_PADDING 40
#define HASHRATE_CHART_AXIS_MAJOR_TICK_LENGTH 8
#define HASHRATE_CHART_AXIS_LABEL_DRAW_SIZE 70
#define HASHRATE_CHART_NAV_HEIGHT 64

#endif // HASHRATE_CHART_LAYOUT_H
